[dataset]
description = ["letter_recognition", "beans", "brain_tumor", "cifar", "cats_and_dogs"]
batch_size = 32
weights = ["imagenet"] # ["imagenet", "finetuning"]

[model]
description = ["resnet18", "resnet34", "resnet50", "resnet101", "resnet152", "mobilenet_v3_small", "mobilenet_v3_large", "maxvit_t"]
n_hidden = 128

##################################################################################

[brkga]
mode = "percent" # ["percent", "absolute"]
n_elites = 0.25
n_offsprings = 0.6
n_mutants = 0.15
bias = 0.7
eliminate_duplicates = false # true or false
threshold_decoding = 0.3 # threshold for binary (select a feature or not)

[optimization]
n_gen = 100
fitness_function = "negative_log_likelihood" # ["negative_log_likelihood", "accuracy"]

##################################################################################

[file]
history = "./log/history/{name}.csv"
best_solution = "./log/best_solutions.csv"
all_results = "./log/experiment_results.csv"