[dataset]
description = ["beans", "brain_tumor", "cats_and_dogs", "letter_recognition", "cifar"]
batch_size = 32
weights = ["imagenet", "finetuned"]

[model]
description = ["resnet18", "resnet34", "mobilenet_v3_small", "maxvit_t"] # ["resnet50", "resnet101", "resnet152", "mobilenet_v3_large"]
n_hidden = 128

##################################################################################

[brkga]
mode = "percent" # ["percent", "absolute"]
n_elites = 0.25
n_offsprings = 0.6
n_mutants = 0.15
bias = 0.7
eliminate_duplicates = false # true or false
threshold_decoding = 0.3 # threshold for binary (select a feature or not)

[optimization]
n_gen = 150
fitness_function = "negative_log_likelihood" # ["negative_log_likelihood", "accuracy"]

##################################################################################

[metrics]
list = ["accuracy", "precision", "recall", "f1", "roc_auc"]
average = "macro" # ["micro", "macro", "weighted", "none"]
multi_class = "ovr" # ["ovr", "ovo"]

[file]
history = "./log/history/{name}.csv"
best_solution = "./log/best_solutions.csv"
all_results = "./log/experiment_results.csv"
evaluation = "./log/evaluation_results.csv"