[dataset]
description = "beans" # ["letter_recognition", "beans", "brain_tumor", "cifar", "cats_and_dogs"]
batch_size = 32

[model]
description = "resnet18" # ["resnet18", "resnet34", "resnet50", "resnet101", "resnet152", "resnet152", "mobilenet_v3_small", "mobilenet_v3_large", "maxvit_t"]
n_hidden = 128

[brkga]
n_elites = 100
n_offsprings = 150 
n_mutants = 50
bias = 0.7
eliminate_duplicates = true # or false

[optimization]
n_gen = 2
fitness_function = "accuracy"
