[dataset]
description = "beans" # ["letter_recognition", "beans", "brain_tumor", "cifar", "cats_and_dogs"]
batch_size = 32

[model]
description = "resnet18" # ["resnet18", "resnet34", "resnet50", "resnet101", "resnet152", "mobilenet_v3_small", "mobilenet_v3_large", "maxvit_t"]
n_hidden = 128

##################################################################################

[brkga]
mode = "percent" # ["percent", "absolute"]
n_elites = 0.25
n_offsprings = 0.85
n_mutants = 0.15
bias = 0.7
eliminate_duplicates = false # true or false
threshold_decoding = 0.3 # threshold for binary (select a feature or not)

[optimization]
n_gen = 15
fitness_function = "negative_log_likelihood" # ["negative_log_likelihood", "accuracy"]

##################################################################################

[cross_validation]
n_splits = 5
n_repeats = 10
random_state = 100
scoring = "accuracy"

[random_forest]
n_estimators = [50, 100]
max_features = ["sqrt", "log2"]
min_samples_leaf = [1, 5]

[metrics]
list = ["accuracy", "precision", "recall", "f1", "roc_auc"]
average = "macro" # ["micro", "macro", "weighted", "none"]
multi_class = "ovr" # ["ovr", "ovo"]